### ISSUE TITLE
Canonical method/example to use Gun with Redux for React

### ISSUE THREAD

**Issue by demorphica** [actuallydan/react-gun#1]
https://stackoverflow.com/questions/57501944/canonical-method-example-to-use-gun-with-redux-for-react

reproducing issue description below -

I am using redux for state management for a dynamic grid where someone can add their own components. I'm using this library for the grid https://github.com/STRML/react-grid-layout . 

I want to use Gun as a persistence layer for storing & replicating the current state of the grid & its components into a user profile. my app does not use Express.js for now so I'm having some issues running the examples since all of them use Express. I'm also using react-gun but I was not able to figure out how to setup the Gun Provider with the Redux Store Provider

is there a canonical method/example to use Gun with Redux for React?

i've tried this

```javascript
import React from 'react';
import ReactDOM from 'react-dom';
import { Provider } from 'react-redux';
import Gun from 'gun';
import { GunProvider } from 'react-gun';
import App from './App';
import configureStore from './redux/store/configureStore';
import * as serviceWorker from './serviceWorker';

const gun = Gun({ file: 'db' });

ReactDOM.render(
  <GunProvider gun={gun}>
    <Provider store={configureStore()}>
      <App />
    </Provider>
  </GunProvider>,
  document.getElementById('root')
);
serviceWorker.unregister();
```
and this 

```javascript
import React from 'react';
import ReactDOM from 'react-dom';
import { Provider } from 'react-redux';
import Gun from 'gun';
import { GunProvider } from 'react-gun';
import App from './App';
import configureStore from './redux/store/configureStore';
import * as serviceWorker from './serviceWorker';

const gun = Gun({ file: 'db' });

ReactDOM.render(
  
  <Provider store={configureStore()}>
    <GunProvider gun={gun}>
      <App />
    </GunProvider>
  </Provider>,
  document.getElementById('root')
);
serviceWorker.unregister();
```

i do not see any errors building or running the app

console log start 
```
[HMR] Waiting for update signal from WDS...
gun.js:863 Hello wonderful person! :) Thanks for using GUN, feel free to ask for help on https://gitter.im/amark/gun and ask StackOverflow questions tagged with 'gun'!
```

console log showing the 'data' variable i logged in the code above

```json
data: Gun
_:
$: Gun {_: {…}}
ack: 1
back: {gun: Gun, $: Gun, opt: {…}, root: {…}, graph: {…}, …}
get: "data"
gun: Gun {_: {…}}
id: 79
on: ƒ onto(tag, arg, as)
put: undefined
root: {gun: Gun, $: Gun, opt: {…}, root: {…}, graph: {…}, …}
soul: "data"
tag: {in: {…}, out: {…}}
__proto__: Object
__proto__: Object
```

but i dont see anything appearing in Chrome >> Application tab >> Local Storage

i see this in ```yarn build``` logs but i am not sure it is related

```
WARNING in ../node_modules/gun/gun.js 10:16-28
Critical dependency: the request of a dependency is an expression
 @ ./index.jsx
```

here's how i use yarn to build/run the project 
package.json

```
  "scripts": {
    "start": "cross-env-shell NODE_ENV=development node --max-old-space-size=12288 node_modules/webpack-dev-server/bin/webpack-dev-server.js --mode development --open",
    "build": "cross-env-shell NODE_ENV=production node --max_old_space_size=12288 node_modules/webpack/bin/webpack.js --mode production",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
```

here's how i use gun in my components

```javascript
import React, { Component, Fragment } from 'react';
import PropTypes from 'prop-types';
import { withGun } from 'react-gun';
import Logger from '../appLogger/logger';

const log = new Logger({
  childType: 'component',
  childName: 'Foo'
});


class Foo extends Component {
  static propTypes = {
    blah: PropTypes.string.isRequired
  };
  constructor(props) {
    super(props);
  }
  componentDidMount() {
    const data = this.props.gun.get('data').once(() => {});
    log.debug({
      msg: '[component] [componentDidMount] MainLayout',
      methodType: 'componentDidMount',
      logObjectName: 'data',
      logObject: data
    });
  }
  
  render() {
    const { blah } = this.props;
    return (
      <div>
        {blah}
      </div>
    );
  }
}

export default withGun(Foo);
```

**Expected results -**

I should see an entry called "gun" Chrome DevTools >> Application tab >> Local Storage

**Actual Results -** 

i dont see anything appearing in Chrome Chrome DevTools >> Application tab >> Local Storage

**Comment by demorphica** [comment]
also tried the following based on a recommendation from @Lightnet from the Gun Gittter thread here https://gitter.im/amark/gun

> ```
> console.log(this.props.gun)
> ```
> 
> i see this in logs
> ```
> Gun
> _:
> $: Gun {_: {…}}
> ask: ƒ ask(cb, as)
> dup: {s: {…}, check: ƒ, track: ƒ, to: null}
> graph: {}
> gun: Gun {_: {…}}
> mum: undefined
> next: {state: {…}, jzbrhtcmcaHlTeChUdpX: {…}, jzbrhtcnU7bQjRGJdyhp: {…}, jzbrhtcn01aniKNTxBBLJWM: {…}, jzbrhtco0EsQyUof1QzV: {…}, …}
> now: undefined
> on: ƒ onto(tag, arg, as)
> once: 79
> opt: {file: "db", peers: {…}, WebSocket: ƒ, log: ƒ, gap: 1, …}
> puts: 2
> root: {gun: Gun, $: Gun, opt: {…}, root: {…}, graph: {…}, …}
> tag: {create: {…}, bye: {…}, hi: {…}, in: {…}, out: {…}, …}
> __proto__: Object
> __proto__: Object
> ```

**Comment by demorphica** [comment]
also recommended by @Lightnet i changed the import statement to the one below

```
import Gun from 'gun/gun';
```

but there is no change in messages, logs or result

**Comment by actuallydan** [comment]
@demorphica , sorry for not responding sooner. Unfortunately, I don't think I'll be much help, as I have neither updated this repository in a long time, nor have I used Gun for quite a while, I decided to forgo using Gun in favor of Redux+Apollo for my persistence and state management.

To answer your question, as far as I know, there aren't any examples of using Gun with Redux, as I imagine the intent was to use it in place of Redux, nor could I personally figure out a non-express solution since everyone decided serverless was the way to go midway through my personal use of Gun.

Again, unfortunately, if no one over in the Gun Gitter was able to point you in the right direction you may be at a loss, as they don't seem to have the bandwidth to cover all the use-cases people are coming up with for the otherwise fantastic library.

In regards to the `Critical dependency: the request of a dependency is an expression` warning, this is just a result of the way Gun is bundled (i.e. not with Webpack or other bundlers in mind) but I haven't heard of it affecting functionality.

I imagine if you really wanted to use Redux and Gun together you'd follow an Observable pattern here you initialize your Redux store and then hook into Gun listeners to call actions and such, but as I said, I've never used the two together, and I haven't seen any examples of it, so you'd have to build it yourself.

I'll update the README noting that this repo is unmaintained.
